# Generated by Django 4.0 on 2022-01-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('colour', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Dress', 'Dress'), ('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Shorts', 'Shorts'), ('Shoes', 'Shoes')], max_length=50)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
