# Generated by Django 4.0 on 2022-01-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedb',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='SimilarityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('column_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_item', to='home.imagedb')),
                ('row_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_item', to='home.imagedb')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.TextField()),
                ('image_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.imagedb')),
            ],
        ),
    ]
