# Generated by Django 4.0 on 2022-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_imagedb_gender_similaritymatrix_featurevector'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurevector',
            name='array_datatype',
            field=models.CharField(default='float32', max_length=10),
        ),
        migrations.AlterField(
            model_name='imagedb',
            name='type',
            field=models.CharField(choices=[('dress', 'Dress'), ('shirt', 'Shirt'), ('pants', 'Pants'), ('shorts', 'Shorts'), ('shoes', 'Shoes')], max_length=50),
        ),
    ]
