# Generated by Django 4.0 on 2022-01-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_featurevector_array_datatype_alter_imagedb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevector',
            name='vector',
            field=models.BinaryField(),
        ),
    ]
