# Generated by Django 4.0 on 2022-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_featurevector_vector_alter_imagedb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevector',
            name='vector',
            field=models.BinaryField(),
        ),
    ]
