# Generated by Django 4.0 on 2022-02-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_featurevector_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('colour', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('image_link_front', models.TextField(blank=True, null=True)),
                ('image_link_back', models.TextField(blank=True, null=True)),
                ('is_custom', models.BooleanField(verbose_name='Is the object uploaded by user')),
                ('gender', models.CharField(blank=True, choices=[('Boys', 'Boys'), ('Men', 'Men'), ('Unisex', 'Unisex'), ('Women', 'Women'), ('Girls', 'Girls')], max_length=10, null=True)),
                ('ageGroup', models.CharField(blank=True, choices=[('Kids-Girls', 'Kids-Girls'), ('Kids-Unisex', 'Kids-Unisex'), ('Kids-Boys', 'Kids-Boys'), ('Adults-Women', 'Adults-Women'), ('Adults-Unisex', 'Adults-Unisex'), ('Adults-Men', 'Adults-Men')], max_length=25, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('season', models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=20, null=True)),
                ('usage', models.CharField(blank=True, choices=[('Formal', 'Formal'), ('Smart Casual', 'Smart Casual'), ('Sports', 'Sports'), ('Party', 'Party'), ('Home', 'Home'), ('NA', 'NA'), ('Ethnic', 'Ethnic'), ('Casual', 'Casual'), ('Travel', 'Travel')], max_length=20, null=True)),
                ('main_category', models.CharField(blank=True, max_length=60, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=60, null=True)),
                ('article_category', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('image_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.imageobject')),
            ],
        ),
        migrations.AlterField(
            model_name='featurevector',
            name='image_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.imageobject'),
        ),
        migrations.AlterField(
            model_name='similaritymatrix',
            name='column_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_item', to='home.imageobject'),
        ),
        migrations.AlterField(
            model_name='similaritymatrix',
            name='row_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_item', to='home.imageobject'),
        ),
        migrations.DeleteModel(
            name='ImageDB',
        ),
    ]
