# Generated by Django 4.0 on 2022-02-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_imageobject_tag_alter_featurevector_image_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageobject',
            old_name='ageGroup',
            new_name='age_group',
        ),
        migrations.AddField(
            model_name='imageobject',
            name='image_buy_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
