# Generated by Django 4.0 on 2022-02-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_agegroup_imageobject_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageobject',
            name='image_link_left',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageobject',
            name='image_link_right',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='is_custom',
            field=models.BooleanField(verbose_name='Object uploaded by user'),
        ),
    ]
