# Generated by Django 4.0 on 2022-03-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0013_useravatarsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatarsocial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
