# Generated by Django 4.0 on 2022-04-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_rechistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechistory',
            name='image',
        ),
        migrations.AddField(
            model_name='rechistory',
            name='image',
            field=models.ManyToManyField(to='home.ImageObject'),
        ),
    ]
