# Generated by Django 4.0 on 2022-04-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_rechistory_image_rechistory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechistory',
            name='image',
        ),
        migrations.AddField(
            model_name='rechistory',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.imageobject'),
        ),
    ]
